### ISSUE TITLE
Fugu14

### ISSUE THREAD

**Issue by SmartBoy84** [evelyneee/ellekit#19]
Dude, it'd be so sick if you could help me get this to work in Fugu14 to achieve a proper untether!
I have **absolute** no clue what I'm doing, this is what I've been able to botch together so far: https://github.com/SmartBoy84/Weazol

Trust cache injection works sometimes for some utilities but doesn't for others, daemon launching is unreliable and device will crash randomly

**Comment by evelyneee** [comment]
You can send me a dm at evln#0001, or talk on the r/Jailbreak discord. I'm saying that if you adapt the current Fugu15 basebinaries to work with the kernel read/write method of iOS 14, you can get a fully working jailbreak. The code should be reusable.
