### ISSUE TITLE
Respring in safe mode seems a bit troublesome.

### ISSUE THREAD

**Issue by invalidunit** [evelyneee/ellekit#27]
Maybe we should open an app like Coolstar does to facilitate normal users to log out after entering safe mode? 
Because sometimes entering safe mode is just caused by a plugin crashing by accident. 
Also, is it a bit strange to only prohibit third-party plug-ins from injecting into SpringBoard in safe mode? From the previous jailbreaking, shouldn't injection into any program be prohibited?

**Comment by evelyneee** [comment]
This is true, but the implementation is annoying. It's on my todo list though
