### ISSUE TITLE
Injection broken on Rootless Palera1n since Update 0.6.1

### ISSUE THREAD

**Issue by iAroc** [evelyneee/ellekit#28]
Heyya

Got a few reports from my users, that the tweak didnt inject anymore. After some debugging, we found that as soon they Update Ellekit in Sileo to anything after 0.6-1 (so 0.6.1 and up) it doesnt load any tweak anymore.

Downgrading and it works directly again.

Most of the Users are on ios 15.x

Do you have any log file that gets generated or something, that can help you with finding the issue?

**Comment by evelyneee** [comment]
Fixed in 0.6.2

**Comment by iAroc** [comment]
But its broken on 0.6.2 and 0.6.3 too, thats why i reported it. Something changed in that versions so it doesnt load correctly anymore it seems, as downgrading and using the same tweak works fine
