### ISSUE TITLE
The project 'ellekit.xcodeproj' does not contain a target named 'ellekit-mac'

### ISSUE THREAD

**Issue by haniag** [evelyneee/ellekit#37]
When I run this command `xcodebuild -target ellekit-mac` in the solutions folder, I get this error `xcodebuild: error: The project 'ellekit.xcodeproj' does not contain a target named 'ellekit-mac'`

If I try changing to `xcodebuild -target ellekit`, then it successfully builds, so how can I make a new build for mac?

SIP disabled
arm64e abi enabled
M2 13.5.1
Xcode 14.3.1

**Comment by lockdownderp** [comment]
@haniag If you run `xcodebuild -list` in the solutions folder you should get the following

```
User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Information about project "ellekit":
    Targets:
        ellekit
        test
        loader
        launchd
        safemode-ui
        ptrauth-shim
        injector

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        ellekit
        ellekit-mac
        injector
        launchd
        loader
        ptrauth-shim
        safemode
        safemode-ui
        test
 ```
 
 Try building with `xcodebuild -scheme ellekit-mac`

**Comment by haniag** [comment]
Thanks a lot, as this worked! I guess I can build everything except the "pspawn.dylib" file.
