### ISSUE TITLE
AppSync Compatibility Request

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [evelyneee/ellekit#39]
This tweak injection doesn't support AppSync correctly - it needs fixes - even the AppSync creator itself says that this incompatibility problem we have is due to the Ellekit itself, not to the AppSync Unified tweak.

Please, look at the following: [https://github.com/akemin-dayo/AppSync/issues/174](https://github.com/akemin-dayo/AppSync/issues/174)

**Comment by evelyneee** [comment]
I fixed this locally but I didn’t push it and my Macbook’s screen cracked and they had to erase it to repair it - I couldn’t get the files and it’ll take a long time to rewrite everything

**Comment by admin-elvistrujanovic** [comment]
> I fixed this locally but I didn’t push it and my Macbook’s screen cracked and they had to erase it to repair it - I couldn’t get the files and it’ll take a long time to rewrite everything

It's ok - thank you for your time - I'm sure this will not last for 5 years so we just need to wait for the update to be pushed. For now I guess we should use TrollStore instead if we're planning to be able to use App Store 😅

**Comment by ghh-jb** [comment]
After 1.1 update it is working. Thank you very much.
