### ISSUE TITLE
[Question] how to replace ellekit dylibs?

### ISSUE THREAD

**Issue by gotschi** [evelyneee/ellekit#45]
Hello, I try to build ellekit with safe mode disabled.

Now I have the dylibs but how do I place them on my ios 16.7 iphone 8 jb rootless with palera1n?

Is it just a matter of replacing them in the FS?

I installed ellekit with zebra

Thank you!!

**Comment by evelyneee** [comment]
Replace /usr/lib/MobileSafety.dylib with /usr/lib/ellekit.dylib

**Comment by gotschi** [comment]
awesome, will try that tonight. thank you for the fast response!

**Comment by gotschi** [comment]
hm, there is no /usr/lib/MobileSafety.dylib on my phone :/

I only have /private/preboot/xxx/jb-DSvxcZJt/procursus/usr/lib/ellekit/MobileSafety.dylib

**Comment by evelyneee** [comment]
Yeah that’s what I meant

**Comment by gotschi** [comment]
seems to work fine so far, thank you!!
