### ISSUE TITLE
ellekit don't load tweak to com.apple.WebKit.WebContent on rootful and rootless jailbreak palerain

### ISSUE THREAD

**Issue by ienthach** [evelyneee/ellekit#47]
i create simple tweak and load to com.apple.WebKit.WebContent. 
It works on **ellekit** roothide. 
it works on **substitute** rootful palerain. 
it dont work on **ellekit** rootful and rootless palerain

**Comment by evelyneee** [comment]
not my problem, talk to palera1n team
