### ISSUE TITLE
v1.1.2 crashes Clock when injection enabled

### ISSUE THREAD

**Issue by Rov3r** [evelyneee/ellekit#49]
Good afternoon,

On Serotonin/Bootstrap, I’ve been using AlarmTime successfully for a week or so and noticed today that the Clock app wouldn’t open.

Even with no tweaks injected, just having Clock enabled in Bootstrap, will crash the app. I did not notice this issue until updating to ElleKit 1.1.2, so I’m hoping to bring this to your attention.

Also: I restarted my device, and re-activated Bootstrap and Serotonin just to be totally sure it’s just an issue with Clock, and it is.

**Comment by dhinakg** [comment]
Does this occur with 1.1.1?

**Comment by Rov3r** [comment]
It turned out to be AutoAlerts that was causing the issue. My bad!
