### ISSUE TITLE
Userspace reboot fails with version 1.1.2

### ISSUE THREAD

**Issue by MuhammadBoubes** [evelyneee/ellekit#50]
Since the release of ellekit 1.1.1 & 1.1.2 the device hangs on a black screen when doing a userspace reboot, requiring a forced reboot and a rejailbreak.
This problem didn't exist in version 1.1
Device: iphone X, ios 16.5, previously jailbroken with palen1x and now jailbroken with dopamine, the problem persisted in both jailbreaks.

**Comment by dhinakg** [comment]
You probably have a bad tweak. Check if this happens with all tweaks removed, but with ElleKit still installed and tweak injection still enabled.

**Comment by MuhammadBoubes** [comment]
When I removed palera1n and installed dopamine, the first tweak I installed was ellekit, and the problem was there. 
Even when trying to activate the jailbreak with tweaks enabled in dopamine, it hangs on a black screen requiring a forced reboot.
My only workaround after a forced reboot was to disable tweaks from dopamine app settings, then activate the jailbreak while tweaks are disabled, then enable tweaks and perform a respring(not a userspace reboot).

**Comment by opa334** [comment]
Make sure lockdown mode is disabled?

**Comment by MuhammadBoubes** [comment]
> Make sure lockdown mode is disabled?

It's disabled.
I think it's a problem of some tweak leftovers on my phone, because other devices reboot properly with the same version of ellekit.
I will remove the jailbreak then erase all contents, hopefully this will solve the issue.
Thank you our super programmer OPA, your achievements will be remembered for decades to come...
