### ISSUE TITLE
macOS  14.5 failed

### ISSUE THREAD

**Issue by lCrassna** [evelyneee/ellekit#54]
nx@NX ~ % sudo /usr/local/bin/loader 
Password:
[+] got task 7683
[i] using path /Library/TweakInject/pspawn.dylib
[+] loader: started thread: 6151
[+] loader: converted thread state
zsh: killed     sudo /usr/local/bin/loader

**Comment by evelyneee** [comment]
crash log?

**Comment by lCrassna** [comment]
log:?
[loader-2024-05-28-182435.ips.zip](https://github.com/evelyneee/ellekit/files/15467816/loader-2024-05-28-182435.ips.zip)

**Comment by lCrassna** [comment]
**### found in frida:**
 if (os_version.majorVersion == 14 && os_version.minorVersion >= 4) {
        thread_terminate(thread);
        error = thread_create_running(task, thread_flavor, (thread_state_t)&machine_thread_state, machine_thread_flavor_count, &thread);
        if (error != KERN_SUCCESS) {
            fprintf(stderr, "could not spawn remote thread: %s\n", mach_error_string(error));
            return 1;
        }
  }
**### swift:**
let create = withUnsafeMutablePointer(to: &state, {
    $0.withMemoryRebound(to: UInt32.self, capacity: MemoryLayout<__darwin_arm_thread_state64>.size, { statePtr in
        thread_terminate(thread);
        return thread_create_running(task, ARM_THREAD_STATE64, statePtr, count, &thread);
    })
})

Is it the solution?
