### ISSUE TITLE
Objective C or static Library 

### ISSUE THREAD

**Issue by malhaar** [evelyneee/ellekit#7]
Hey, Thanks for reply on other issue and apologies for creating new issue, but can you please add how to's for objc if you have time? or Static Library Target in current project which will generate static lib and header to use on jailed device?

Regards,

**Comment by evelyneee** [comment]
If you build the library in Xcode, you'll get a dynamic library you can use just like Substrate. This will use MSHookMessageEx, just like Cydia Substrate, so existing tweaks work.

**Comment by malhaar** [comment]
i wanted to use it on non-jailbroken tweak.
