### ISSUE TITLE
"loader" got killed immediately when running on Mac M1 (Ventura)

### ISSUE THREAD

**Issue by MakaiKnight94** [evelyneee/ellekit#8]
Hi @evelyneee, 
I've tried to run the `loader` either built from Xcode or the one you attached in the "issue-2" on a Mac M1 mini terminal and it got killed immediately. I also setup the plist to run it with launchd like you show in the instruction. Both the output log and the error log were empty so I assumed it also got killed during the startup process. I tried to disable SIP but still have the same result when running the `loader`. The only thing that got me a little bit further is creating a new Command Line Tool target and moving all the code of `loader` to the new target. That got me as far as to the `set thread state` as following:
```
[+] got task 7427
[i] using path /Library/TweakInject/pspawn.dylib
[+] loader: started thread
[+] loader: converted thread state
[-] loader: failed to set thread state
```

Is there anything specific I need to do for the loader to work on the Mac M1 (currently on Ventura)?

**Comment by evelyneee** [comment]
You need to enable the arm64e abi and disable sip

**Comment by MakaiKnight94** [comment]
Thank you @evelyneee! Turning arm64e abi and recompile for arm64e did help to make it work for me. But now I face a new problem when I create a very basic tweaks that just print a hello world. When I put the `.dylib` and `.plist` file into the /Library/TweakInject folder and reboot the userspace, it seems to crashes many apps on the OS such as SpotLight (search), Archive Utility, also my test app which I put the bundle id in the ".plist" file
