### ISSUE TITLE
Where can we get pspawn.dylib for ios?

### ISSUE THREAD

**Issue by abxyap** [evelyneee/ellekit#9]
Hi @evelyneee,

Where can we get pspawn.dylib if want to load ellekit in 

fugu15,Thanks...

**Comment by evelyneee** [comment]
Hello,

ElleKit no longer uses pspawn.dylib in Fugu15. You need a private Fugu15 build for it to work.

**Comment by abxyap** [comment]
Thanks for replying ,or could you share the pspawn.dylib you used in the demo ?

**Comment by evelyneee** [comment]
No. That version was intended for private use and does not work on normal fugu

**Comment by abxyap** [comment]
Ok.Thanks for replying~
